__rethrow_casa_exceptions = True
h_init()
try:
    hifa_restoredata (vis=['uid___A002_Xc733ea_X753', 'uid___A002_Xc772ca_X392', 'uid___A002_Xca2b8a_X6be2', 'uid___A002_Xcbdb2a_X6e67', 'uid___A002_Xcbdb2a_X8114', 'uid___A002_Xcbdb2a_X13ce2', 'uid___A002_Xcc10e0_X6dd3', 'uid___A002_Xcc3ae3_X95bc', 'uid___A002_Xccb526_Xcc36', 'uid___A002_Xccb526_Xd6ae'], session=['session_1', 'session_2', 'session_3', 'session_4', 'session_5', 'session_6', 'session_7', 'session_8', 'session_11', 'session_11'], ocorr_mode='ca')
finally:
    h_save()
