__rethrow_casa_exceptions = True
h_init()
try:
    hifa_restoredata (vis=['uid___A002_Xc5ceeb_X833', 'uid___A002_Xc5fe11_X4c9', 'uid___A002_Xc62c80_X285', 'uid___A002_Xc68865_X432', 'uid___A002_Xc845c0_X2fea', 'uid___A002_Xc94c38_X66e8', 'uid___A002_Xca9e6b_Xe6c8', 'uid___A002_Xcaca82_X43f0'], session=['session_1', 'session_2', 'session_3', 'session_5', 'session_7', 'session_10', 'session_11', 'session_12'], ocorr_mode='ca')
finally:
    h_save()
